import { Orbitron, Rajdhani } from 'next/font/google';
import "./globals.css";
import BackgroundMusic from '@/components/BackgroundMusic';

const orbitron = Orbitron({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
  variable: '--font-orbitron',
});


export const metadata = {
  title: "Hash For Gamers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${orbitron.variable}`}
      >
        {children}
        <BackgroundMusic/>
      </body>
    </html>
  );
}
